services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: messenger
      POSTGRES_PASSWORD: messenger
      POSTGRES_DB: messenger
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U messenger"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  server:
    build: ./server
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: messenger
      DB_USER: messenger
      DB_PASSWORD: messenger
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "50051:50051"

volumes:
  db_data:
  redis_data:
