name: build-windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-qt5

    - name: Configure & Build (CMake + Ninja)
      shell: msys2 {0}
      run: |
        mkdir -p build
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        ninja

    - name: Upload executables
      uses: actions/upload-artifact@v3
      with:
        name: messenger-executables
        path: |
          build/**/*.exe


    - name: Upload raw EXEs
      uses: actions/upload-artifact@v3
      with:
        name: messenger-executables
        path: |
          messenger_server/build/*.exe
          messenger_client/build/*.exe

