name: Build Messenger (Windows/MSYS2)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # MSYS2 с полным набором пакетов, которые требует твой CMake
      - name: Setup MSYS2 with deps
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            pkgconf
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            # Qt6 для GUI (uic/moc/rcc внутри qt6-tools)
            mingw-w64-x86_64-qt6-base
            mingw-w64-x86_64-qt6-tools
            mingw-w64-x86_64-qt6-svg
            # gRPC/Protobuf для shared, client-core, server
            mingw-w64-x86_64-protobuf
            mingw-w64-x86_64-grpc
            # Крипто/БД для client-core и server
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-sqlite3
            # Зависимости сервера
            mingw-w64-x86_64-libpqxx
            mingw-w64-x86_64-postgresql
            mingw-w64-x86_64-hiredis
            mingw-w64-x86_64-argon2

      - name: Configure (CMake, Ninja, Release)
        shell: msys2 {0}
        run: |
          set -e
          mkdir -p build
          cd build
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          ninja -v

      - name: Collect executables
        shell: msys2 {0}
        run: |
          set -e
          cd build
          # выведем список .exe, чтобы в логах видно было, что собралось
          find . -name "*.exe" -print

      - name: Upload executables (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: messenger-executables
          path: |
            build/**/*.exe
          if-no-files-found: error

