name: build-windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-qt6-base
          mingw-w64-x86_64-qt6-tools
          mingw-w64-x86_64-qt6-svg
          mingw-w64-x86_64-protobuf
          mingw-w64-x86_64-grpc
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-sqlite3
          mingw-w64-x86_64-libpqxx
          mingw-w64-x86_64-postgresql
          mingw-w64-x86_64-hiredis
          mingw-w64-x86_64-argon2

    - name: Build Server
      shell: msys2 {0}
      run: |
        cd messenger_server
        mkdir -p build
        cd build
        cmake .. -G "Ninja"
        ninja

    - name: Build Client (Qt)
      shell: msys2 {0}
      run: |
        cd messenger_client
        mkdir -p build
        cd build
        cmake .. -G "Ninja"
        ninja

    - name: Run tests (if any)
      shell: msys2 {0}
      run: |
        if [ -d messenger_server/build ]; then ctest --test-dir messenger_server/build --output-on-failure || true; fi
        if [ -d messenger_client/build ]; then ctest --test-dir messenger_client/build --output-on-failure || true; fi

    - name: Upload raw EXEs
      uses: actions/upload-artifact@v4
      with:
        name: messenger-executables
        path: |
          messenger_server/build/*.exe
          messenger_client/build/*.exe


